server:
  port: 8080
spring:
  application:
    name: gateway-services
  cloud:
    consul:
      discovery:
        register: false
        registerHealthCheck: false
      config:
        enabled: false
      host: localhost
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/music/**
          filters:
            - RewritePath=/music/(?<path>.*), /music/$\{path}
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
          filters:
            - RewritePath=/songs/(?<path>.*), /songs/$\{path}
        - id: playlist-service
          uri: lb://playlist-service
          predicates:
            - Path=/playlists/**
          filters:
            - RewritePath=/playlists/(?<path>.*), /playlists/$\{path}
        - id: auth-service
          uri: http://localhost:9100
          predicates:
            - Path=/auth/**
            - Method=POST
          filters:
            - RewritePath=/auth/(?<path>.*), /auth/$\{path}